=== ebi-uniprot/ProtVista/documentation/sequenceFeaturesJsonSchema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "http://jsonschema.net",
	"type": "object",
	"properties": {
		"accession": {
			"type": "string"
		},
		"entryName": {
			"type": "string"
		},
		"sequence": {
			"type": "string"
		},
		"sequenceVersion": {
			"type": "string"
		},
		"eGeneId": {
			"type": "string"
		},
		"eProteinId": {
			"type": "string"
		},
		"categories": {
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"$ref": "#/definitions/categoryObject"
			}
		}
	},
	"required": ["accession", "entryName", "sequence", "sequenceVersion", "categories"],
	"definitions": {
		"categoryObject": {
			"properties": {
				"category": {
					"type": "string"
				},
				"categoryAbbrev": {
					"type": "string",
					"pattern": "^(MOL_PROC|STR_FT|DOM_SITE|PTM|NAT_VAR|MUTA|SEQ_INFO|TOPO)$"
				},
				"types": {
					"type": "array",
					"items": {
						"type": "object",
						"$ref": "#/definitions/typeObject"
					}
				}
			},
			"required": ["category", "types"]
		},
		"typeObject": {
			"properties": {
				"type": {
					"type": "string"
				},
				"label": {
					"type": "string"
				},
				"cvId": {
					"type": "string"
				},
				"locations": {
					"type": "array",
					"items": {
						"type": "object",
						"$ref": "#/definitions/locationObject"
					},
					"minItems": 1
				}
			},
			"required": ["type", "label", "locations"]
		},
		"locationObject": {
			"properties": {
				"locationType": {
					"enum": ["CONTINUOUS", "BRIDGE", "POSITION"]
				},
				"features": {
					"type": "array",
					"items": {
						"type": "object",
						"anyOf": [
							{
								"$ref": "#/definitions/featureObject"
							}, {
								"$ref": "#/definitions/variantObject"
							}
						]							
					},
					"minItems": 1
				}
			},
			"required": ["locationType", "features"]
		},
		"featureObject": {
			"properties": {
				"ftId": {
					"type": "string",
					"unique": true
				},
				"internalId": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"begin": {
					"type": "integer",
					"minimum": 1
				},
				"end": {
					"type": "integer",
					"minimum": 1
				},
				"status": {
					"type": "string"
				},
				"evidence": {
					"type": "array",
					"items": {
						"type": "object",
						"$ref": "#/definitions/evidenceObject"
					},
					"minItems": 1
				}
			},
			"required": ["ftId", "begin", "end"]
		},
		"variantObject": {
			"properties": {
				"ftId": {
					"type": "string",
					"unique": true
				},
				"internalId": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"begin": {
					"type": "integer",
					"minimum": 1
				},
				"end": {
					"type": "integer",
					"minimum": 1
				},
				"status": {
					"type": "string"
				},
				"wildType": {
					"type": "string",
					"pattern": "^(A|R|N|D|C|Q|E|G|H|I|L|K|M|F|P|S|T|W|Y|V)$"
				},
				"mutation": {
					"type": "string",
					"pattern": "^(A|R|N|D|C|Q|E|G|H|I|L|K|M|F|P|S|T|W|Y|V|-|\\*){1,2}$"
				},
				"frequency": {
					"type": "number",
					"minimum": 0,
					"maximum": 1.0
				},
				"polyphenPrediction": {
					"type": "string"
				},
				"polyphenScore": {
					"type": "number",
					"minimum": 0,
					"maximum": 1.0
				},
				"siftPrediction": {
					"type": "string"
				},
				"siftScore": {
					"type": "number",
					"minimum": 0,
					"maximum": 1.0
				},
				"somaticStatus": {
					"type": "integer",
					"minimum": 0,
					"maximum": 1
				},
				"cytogeneticBand": {
					"type": "string"
				},
				"genomicLocation": {
					"type": "string"
				},
				"association": {
					"type": "string"
				},
				"sourceIds": {
		            "type": "array",
		            "minItems": 1,
		            "items": { "type": "string" },
		            "uniqueItems": true
		        },
		        "clinicalSignificances": {
		            "type": "array",
		            "minItems": 1,
		            "items": { "type": "string" },
		            "uniqueItems": true
		        },
				"evidence": {
					"type": "array",
					"items": {
						"type": "object",
						"$ref": "#/definitions/evidenceObject"
					},
					"minItems": 1
				}
			},
			"required": ["ftId", "begin", "end", "wildType", "mutation", "frequency", "polyphenPrediction", "polyphenScore", "siftPrediction", "siftScore"]
		},
		"evidenceObject": {
			"properties": {
				"type": {
					"type": "string",
					"pattern": "^ECO:[0-9]{7}$"
				},
				"source": {
					"type": "object",
					"oneOf": [
						{
							"$ref": "#/definitions/dbReferenceObject"
						}, {
							"$ref": "#/definitions/referenceObject"
						}
					]
				}
			},
			"required": ["type", "source"]
		},
		"dbReferenceObject": {
			"properties": {
				"dbReferenceType": {
					"type": "string"
				},
				"dbReferenceId": {
					"type": "string"
				}
			},
			"required": ["dbReferenceType", "dbReferenceId"]
		},
		"referenceObject": {
			"properties": {
				"ref": {
					"type": "string"
				}
			},
			"required": ["ref"]
		}
	}
}

=== ebi-uniprot/ProtVista/documentation/P05067.json
{
    "accession" : "P05067",
    "entryName" : "A4_HUMAN",
    "sequence" : "MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTNIKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN",
    "sequenceVersion" : "12345",
    "eGeneId" : "ENSG00000142192",
    "eProteinId" : "ENSP00000284981",
    "categories" : [{
        "category" : "Molecule processing",
        "types" : [{
            "type" : "SIGNAL",
            "label" : "signal peptide",
            "cvId" : "SO:0000418",
            "locations" : [{
                "locationType" : "CONTINUOUS",
                "features" : [{
                    "ftId" : "SIGNAL_0",
                    "description" : "",
                    "begin" : 1,
                    "end" : 17,
                    "status" : "Experimental"
                }]
            }]
        }, {
            "type" : "PEPTIDE",
            "label" : "peptide",
            "cvId" : "SO:0001064",
            "locations" : [{
                "locationType" : "CONTINUOUS",
                "features" : [{
                    "ftId" : "PEPTIDE_0",
                    "internalId" : "PRO_0000000095",
                    "description" : "P3(42)",
                    "begin" : 688,
                    "end" : 713,
                    "status" : "Experimental"
                }, {
                    "ftId" : "PEPTIDE_1",
                    "internalId" : "PRO_0000000096",
                    "description" : "P3(40)",
                    "begin" : 688,
                    "end" : 711,
                    "status" : "Experimental"
                }]
            }]
        }, {
            "type" : "CHAIN",
            "label" : "chain",
            "cvId" : "SO:0000419",
            "locations" : [{
                "locationType" : "CONTINUOUS",
                "features" : [{
                    "ftId" : "CHAIN_0",
                    "internalId" : "PRO_0000000088",
                    "description" : "Amyloid beta A4 protein",
                    "begin" : 18,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_1",
                    "internalId" : "PRO_0000000089",
                    "description" : "Soluble APP-alpha",
                    "begin" : 18,
                    "end" : 687,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_2",
                    "internalId" : "PRO_0000000090",
                    "description" : "Soluble APP-beta",
                    "begin" : 18,
                    "end" : 671,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_3",
                    "internalId" : "PRO_0000381966",
                    "description" : "N-APP",
                    "begin" : 18,
                    "end" : 286,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_4",
                    "internalId" : "PRO_0000000091",
                    "description" : "C99",
                    "begin" : 672,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_5",
                    "internalId" : "PRO_0000000092",
                    "description" : "Beta-amyloid protein 42",
                    "begin" : 672,
                    "end" : 713,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_6",
                    "internalId" : "PRO_0000000093",
                    "description" : "Beta-amyloid protein 40",
                    "begin" : 672,
                    "end" : 711,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_7",
                    "internalId" : "PRO_0000000094",
                    "description" : "C83",
                    "begin" : 688,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_8",
                    "internalId" : "PRO_0000384574",
                    "description" : "C80",
                    "begin" : 691,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_9",
                    "internalId" : "PRO_0000000097",
                    "description" : "Gamma-secretase C-terminal fragment 59",
                    "begin" : 712,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_10",
                    "internalId" : "PRO_0000000098",
                    "description" : "Gamma-secretase C-terminal fragment 57",
                    "begin" : 714,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_11",
                    "internalId" : "PRO_0000000099",
                    "description" : "Gamma-secretase C-terminal fragment 50",
                    "begin" : 721,
                    "end" : 770,
                    "status" : "Experimental"
                }, {
                    "ftId" : "CHAIN_12",
                    "internalId" : "PRO_0000000100",
                    "description" : "C31",
                    "begin" : 740,
                    "end" : 770,
                    "status" : "Experimental"
                }]
            }]
        }]
    }, {
        "category" : "Structural features",
        "types" : [{
            "type" : "DISULFID",
            "label" : "disulfide bond",
            "cvId" : "MOD:00689",
            "locations" : [{
                "locationType" : "BRIDGE",
                "features" : [{
                    "ftId" : "DISULFID_0",
                    "description" : "",
                    "begin" : 38,
                    "end" : 62,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_1",
                    "description" : "",
                    "begin" : 73,
                    "end" : 117,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_2",
                    "description" : "",
                    "begin" : 98,
                    "end" : 105,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_3",
                    "description" : "",
                    "begin" : 133,
                    "end" : 187,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_4",
                    "description" : "",
                    "begin" : 144,
                    "end" : 174,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_5",
                    "description" : "",
                    "begin" : 158,
                    "end" : 186,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_6",
                    "description" : "",
                    "begin" : 291,
                    "end" : 341,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_7",
                    "description" : "",
                    "begin" : 300,
                    "end" : 324,
                    "status" : "Experimental"
                }, {
                    "ftId" : "DISULFID_8",
                    "description" : "",
                    "begin" : 316,
                    "end" : 337,
                    "status" : "Experimental"
                }]
            }]
        }, {
            "type" : "HELIX",
            "label" : "helix",
            "cvId" : "SO:0001117",
            "locations" : [{
                "locationType" : "CONTINUOUS",
                "features" : [{
                    "ftId" : "HELIX_0",
                    "begin" : 66,
                    "end" : 76,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_1",
                    "begin" : 100,
                    "end" : 102,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_2",
                    "begin" : 147,
                    "end" : 160,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_3",
                    "begin" : 288,
                    "end" : 292,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_4",
                    "begin" : 334,
                    "end" : 341,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_5",
                    "begin" : 374,
                    "end" : 380,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_6",
                    "begin" : 389,
                    "end" : 418,
                    "status" : "Experimental"
                }, {
                    "ftId" : "HELIX_7",
                    "begin" : 425,
